### ISSUE TITLE
KeyError : 'commanders'

### ISSUE THREAD

**Issue by AmhyrVar** [lheyberger/mtg-parser#1]
when trying to parse this deck : https://www.moxfield.com/decks/y3jaB-HrCEO4YMklNsH4vA

using :

d_url = "https://www.moxfield.com/decks/y3jaB-HrCEO4YMklNsH4vA"
cards = mtg_parser.moxfield.parse_deck(url)
for card in cards:
	print(card)

I have this : 
KeyError                                  Traceback (most recent call last)
<ipython-input-179-11fe67992387> in <module>
----> 1 for card in cards:
      2         print(card)

~\anaconda3\envs\data\lib\site-packages\mtg_parser\moxfield.py in _parse_deck(deck)
     33 
     34 def _parse_deck(deck):
---> 35     for key, value in deck['commanders'].items():
     36         yield Card(key, value['quantity'], tags=['commander'])
     37 

KeyError: 'commanders'

**Comment by lheyberger** [comment]
Fixed in https://github.com/lheyberger/mtg-parser/releases/tag/v0.0.1-alpha.16
