### ISSUE TITLE
Issue in parsing mtggoldfish

### ISSUE THREAD

**Issue by androsovav** [lheyberger/mtg-parser#10]
While parsing some mtggoldfish decks with next code:

cards = mtg_parser.mtggoldfish.parse_deck(url)
for card in cards:
    print(card)

Occurs:
Traceback (most recent call last):
  File "/Users/macbookair/Public/cedh_data_miner/databaseProcessing/a.py", line 8, in <module>
    for card in cards:
                ^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/mtg_parser/mtggoldfish.py", line 40, in _parse_deck
    last_category = row.th.string.strip().splitlines()[0].lower()
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'

This happens only if deck has a modified land, so heading above lands section is not "Lands (34)" but "Lands (34) _+1 MDFC_"

You can try it with these URLs:
https://www.mtggoldfish.com/deck/5887226#paper
https://www.mtggoldfish.com/deck/5864817#paper
https://www.mtggoldfish.com/deck/5633606#paper

**Comment by lheyberger** [comment]
Fixed is released in version 0.0.1a36 (https://github.com/lheyberger/mtg-parser/releases/tag/v0.0.1a36)

**Comment by androsovav** [comment]
I want to create a convenient tool for analyzing statistics from cedh tournaments. I get a database of events from the website edhtop16.com. Then, with the help of your project, I download the participants' decklists. Using the resulting database, I can analyze the win rate trends of individual cards, combinations, or commanders. So, for example, I have already found very strong but not popular white cedh staple - Touch the Spirit Realm. I know which staples are overrated or underrated, which wincons are stronger, and I can also analyze some non-obvious principles of deck building, such as, for example, what number of counterspells is most effective to have in deck (10-12). Everything is great, but progress is not very fast, because I'm not even a junior programmer :)
