### ISSUE TITLE
Hero <3 Thank you :)

### ISSUE THREAD

**Issue by Dimfred** [lheyberger/mtg-parser#8]

**Comment by lheyberger** [comment]
Thanks 🙇‍♂️ I'm glad this library can be of any help!
Care to share how you are using it?

**Comment by Dimfred** [comment]
Sure :)

https://github.com/Dimfred/magic-circle-backend/blob/main/magic_circle/card/parser.py#L81
https://github.com/Dimfred/magic-circle-frontend

Not much docs yet. But basically a sharing app for my circle

**Comment by lheyberger** [comment]
Enjoy :) Don't hesitate to raise any issue you might find ! Or if there's a website I don't support. It's been a long time since I haven't done some due diligence.

**Comment by Dimfred** [comment]
Will do thx mate
